### ISSUE TITLE
Allow customisation of khanify text

### ISSUE THREAD

**Issue by darthsteven** [computerminds/cm-hubot#16]
We should allow khanify to expand text in a customisable way, so if we said:

    juuune

It would get expanded to

    juuuuuuuuune

so it should look for three vowels in a row and expand those.

**Comment by greggadsdon** [comment]
may as well be any letter, not just vowels

**Comment by darthsteven** [comment]
meh

@greggadsdon Code you need to change is here:

https://github.com/computerminds/cm-hubot/blob/master/scripts/meme_captain.coffee#L213

**Comment by greggadsdon** [comment]
@darthsteven made changes

**Comment by darthsteven** [comment]
@greggadsdon nicely done!

![love it](http://i.memecaptain.com/gend_images/CKo0mg.jpg)
