### ISSUE TITLE
Only notify groups when actually mentioned

### ISSUE THREAD

**Issue by anotherjames** [computerminds/cm-hubot#21]
@JWsomething doesn't notify me.

But @Covsomething will notify all those in the @cov group. (And likewise for the other groups defined in group-message.coffee.

This is particularly an issue when posting something from twitter that comes from something like @coventrycc, we don't all need notifying of it!

**Comment by darthsteven** [comment]
![hipchat](https://cloud.githubusercontent.com/assets/95782/26632712/e9feddf2-4608-11e7-8da7-cde386697f19.png)

**Comment by darthsteven** [comment]
At the moment the regex is this:

> /@cov(entry)?/i

Maybe we should try and match whitespace after or end of line

**Comment by anotherjames** [comment]
IIRC, hipchat's sassy (or some other bot) can do groups, is it worth just using that instead? (assuming it doesn't have this bug)

**Comment by darthsteven** [comment]
Sassy is _per room_.

> /@cov(entry)?(?=\s|$)/i

should do the trick!

**Comment by darthsteven** [comment]
Totes works
